### ISSUE TITLE
NVFlex install

### ISSUE THREAD

**Issue by samhodge** [pedohorse/Houdini-NvFlex#12]
How you do get the source for NVFlex.

I signed up on the NVIDIA developer site but I have yet to receive a response.

**Comment by pedohorse** [comment]
i just want to point out 2 things first:
1 - you dont need the flex source to compile this plugin
2 - you dont need any confirmation or anything from nvidia to download flex library with headers - just register and login to their site and go here, available for free https://developer.nvidia.com/gameworksdownload#?search=flex

so the only thing you might need a response to get - is the access to their git repository of a dev version of flex. I did not use anything from there, used only stable version from the link above
Unfortunately they still dont have the sources for core flex library there - they keep it proprietary

**Comment by samhodge** [comment]
Rockin good news!
I was confused as hell, they never responded with my GitHub authorisation.
But you have answered all of my questions, chances are I can get a build under CentOS 6.5 done in the near future.

**Comment by pedohorse** [comment]
glad it helped)

for centOS 6.5 - the only major problem is that it has glibc 2.12 or smth around that, the current binary was compiled with stable debian, glibc 2.24
i don't currently have centos or a virtual machine with it, not sure if i can compile it to link with older version of glibc from my machine,

But you can do it yourself - you just need to change paths in linux_build_165.sh to where your flex library is and where your houdini is, and it should work straight away
I actually compiled it for centOS 6.5 this way at work, but i cannot take home anything from there to share(
to compile you will just need latest nvidia drivers, if im correctly recalling, you will not need cuda toolkit... well, if you do encounter problems with cuda or cudart libs - you will have to get the cuda toolkit and have it's lib paths properly configured, or add it manually to Makefile (yeah, toolkit is 1GB monster, and you need just 2 libraries from there...)

**Comment by samhodge** [comment]
Nah its no problem I have been compiling for fun and profit for a number of years now it should be OK. A few days ago I managed to get around a glibc 2.11 issue and put on a glibc 2.14 onto the host CentOS 6.5 system and it somehow worked.

I think we have some cuda stuff, not sure if it is just drivers or if we have all of the toolkit as well.

Anyway nothing a few downloads and patience of configuring cant fix.

Keen to try it out, no need for binaries when you have given the source out, thanks for that.

**Comment by samhodge** [comment]
We got it working under Centos 6 as a network install, given that it is statically linked, you are right its simple enough.

**Comment by pedohorse** [comment]
great !
